import Head from "next/head";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import Results from "@/components/Results";
import { GetServerSideProps } from "next/types";
import requests from "@/utils/requests";

export default function Home(props) {
  console.log({props});
  
  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header/>

      {/* Nav */}
      <Nav/>

      {/* Results */}
      <Results/>
    </>
  );
}

export async function getServerSideProps(context): GetServerSideProps {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url}` || requests.fetchTrending.url);
  const results = await request.json();

  return {
    props:{
      results
    }
  }
}